[project]
name = "effective-python"
version = "0.1.0"
description = ""
authors = [{ name = "Krzysztof Misztal" }]
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1",
    "jupyterlab-rise>=0.42",
    "numpy>=1.26",
    "pandas>=2.2",
    "matplotlib>=3.8",
    "scikit-learn>=1.4",
    "numba>=0.59",
    "cython>=3.0",
    "line-profiler>=4.1",
    "rich>=13",
    "tqdm>=4.66",
    "django>=4.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
